### PR TITLE
[CI] Install node/yarn

### PR DESCRIPTION
**Pull request by jerboaa**
I've got the UI almost ready to go, but it'll need node/yarn for deployment. This adds the deps.
It should do no harm.

### CODE REVIEW

**Comment by Karm** [comment]
@jerboaa Changing Ubuntu version to 20 is a no-go for native build's glibc. The server is based on CentOS 8 Stream and it sports Glibc 2.28.

On the other hand, we can take this as an opportunity for creating a completely statically linked Quarkus app :smiley:

**Comment by jerboaa** [comment]
> @jerboaa Changing Ubuntu version to 20 is a no-go for native build's glibc. The server is based on CentOS 8 Stream and it sports Glibc 2.28.

Hmm, OK. The runner will be out of support soon, fwiw:
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

**Comment by jerboaa** [comment]
@Karm Updated. Back at `18.04`, but this will break soon.

**Comment by Karm** [comment]
Sigh.
```
Run npm install -g yarn@1.22.17
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
```

**Comment by jerboaa** [comment]
> Sigh.
> 
> ```
> Run npm install -g yarn@1.22.17
> node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
> ```

OK. I'll see if we can do some tricks to only do the native image build on Ubuntu 18.04.

**Comment by Karm** [comment]
@jerboaa Thx. Should be possible. After all the npm dependency hell settles, it's just JavaScript and HTML assets baked in the native-image as resources, right? So adding a Ubuntu 20 stage -> cache frontend build -> Ubuntu 18 stage for native-image build.   It's just the deploy workflow that needs U 18 so as the executable runs on Centos 8 Stream.

I'll play with Ubuntu 20 on my VM now and see about the glibc legacy...

**Comment by Karm** [comment]
@jerboaa 
- quick research: would have to duplicate the whole gcc toolchain in chroot on Ubuntu to use older one IMHO; gonna try
- fully statically linked native image would require us to produce JDK static libs built with musl too, not just glibc... We don't ship that as you know... 
```
Error: Building images for org.graalvm.nativeimage.Platform$LINUX_AMD64 (target libc: musl) requires static JDK libraries.
Use most recent JDK from https://github.com/graalvm/labs-openjdk-*/releases
Missing libraries: java, nio, net, zip
(search path: /home/karm/workspaceRH/mandrel-release/mandrel-java17-22.2.0.0-Final/lib/static/linux-amd64/musl)
com.oracle.svm.core.util.UserError$UserException: Building images for org.graalvm.nativeimage.Platform$LINUX_AMD64 (target libc: musl) requires static JDK libraries.
Use most recent JDK from https://github.com/graalvm/labs-openjdk-*/releases
Missing libraries: java, nio, net, zip
(search path: /home/karm/workspaceRH/mandrel-release/mandrel-java17-22.2.0.0-Final/lib/static/linux-amd64/musl)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:72)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.guarantee(UserError.java:96)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.NativeLibraries.initCLibraryPath(NativeLibraries.java:350)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.c.NativeLibraries.<init>(NativeLibraries.java:264)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeLibraries(NativeImageGenerator.java:1071)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:896)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

**Comment by Karm** [comment]
O.K., containers to the rescue, we will build with builder image...

**Comment by Karm** [comment]
@jerboaa I gave up and switched to builder image. It's likely cleaner than chrooting whole older C toolchain on the GithubActions worker...

**Comment by jerboaa** [comment]
> @jerboaa I gave up and switched to builder image. It's likely cleaner than chrooting whole older C toolchain on the GithubActions worker...

Makes sense. Thanks!

**Pull request merged**
